// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_lniJOLI42IpiOku38UiXX04AlJ1y2j0',
    appId: '1:1015708422039:web:5745ff0b7931d18d71fed2',
    messagingSenderId: '1015708422039',
    projectId: 'bigbys-management',
    authDomain: 'bigbys-management.firebaseapp.com',
    databaseURL: 'https://bigbys-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigbys-management.firebasestorage.app',
    measurementId: 'G-MTY2H98N4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7s8JE0QLiP6TL4h1sTewgwvB_v_igtHo',
    appId: '1:1015708422039:android:4434eea7c6c8c70071fed2',
    messagingSenderId: '1015708422039',
    projectId: 'bigbys-management',
    databaseURL: 'https://bigbys-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigbys-management.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_lniJOLI42IpiOku38UiXX04AlJ1y2j0',
    appId: '1:1015708422039:web:8bb7226b3e3df03671fed2',
    messagingSenderId: '1015708422039',
    projectId: 'bigbys-management',
    authDomain: 'bigbys-management.firebaseapp.com',
    databaseURL: 'https://bigbys-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigbys-management.firebasestorage.app',
    measurementId: 'G-L6PEK8L8G6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapDQs5h-4QwCune122VLVHdn00pj53s4',
    appId: '1:1015708422039:ios:e994b1f696bd6aae71fed2',
    messagingSenderId: '1015708422039',
    projectId: 'bigbys-management',
    databaseURL: 'https://bigbys-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigbys-management.firebasestorage.app',
    iosBundleId: 'com.example.teamCollab',
  );

}